// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    CarbonCampsite: typeof import('~icons/carbon/campsite')['default']
    CarbonDicomOverlay: typeof import('~icons/carbon/dicom-overlay')['default']
    CarbonLanguage: typeof import('~icons/carbon/language')['default']
    CarbonLogoGithub: typeof import('~icons/carbon/logo-github')['default']
    CarbonMoon: typeof import('~icons/carbon/moon')['default']
    CarbonPedestrian: typeof import('~icons/carbon/pedestrian')['default']
    CarbonSun: typeof import('~icons/carbon/sun')['default']
    CarbonWarning: typeof import('~icons/carbon/warning')['default']
    ClassSelector: typeof import('./components/ClassSelector.vue')['default']
    FeatherArrowLeft: typeof import('~icons/feather/arrow-left')['default']
    FeatherIconsArrowLeft: typeof import('~icons/feather/icons-arrow-left')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    PaginationButton: typeof import('./components/PaginationButton.vue')['default']
    README: typeof import('./components/README.md')['default']
    RowsPerPageSelector: typeof import('./components/RowsPerPageSelector.vue')['default']
    TextInput: typeof import('./components/TextInput.vue')['default']
    UserRow: typeof import('./components/UserRow.vue')['default']
    UserSearch: typeof import('./components/UserSearch.vue')['default']
  }
}

export { }
