// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ClassSelector: typeof import('./components/ClassSelector.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    PaginationButton: typeof import('./components/PaginationButton.vue')['default']
    README: typeof import('./components/README.md')['default']
    RowsPerPageSelector: typeof import('./components/RowsPerPageSelector.vue')['default']
    TextInput: typeof import('./components/TextInput.vue')['default']
    UserRow: typeof import('./components/UserRow.vue')['default']
  }
}

export { }
